package pl.lodz.p.it.zzpj.dogs.model;

import lombok.Builder;
import lombok.Data;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

import java.util.HashMap;
import java.util.Map;
import java.util.UUID;

@Document("accounts")
@Builder
public @Data class Account {

    @Id
    @Builder.Default
    private String id = UUID.randomUUID().toString();
    private String username;
    private String password;
    private String firstName;
    private String lastName;
    @Builder.Default
    private Map<String, Double> breedPreferences = new HashMap<>() {{
        put("affenpinscher", 1.0);
        put("african", 1.0);
        put("airedale", 1.0);
        put("akita", 1.0);
        put("appenzeller", 1.0);
        put("basenji", 1.0);
        put("beagle", 1.0);
        put("bluetick", 1.0);
        put("borzoi", 1.0);
        put("bouvier", 1.0);
        put("boxer", 1.0);
        put("brabancon", 1.0);
        put("briard", 1.0);
        put("cairn", 1.0);
        put("chihuahua", 1.0);
        put("chow", 1.0);
        put("clumber", 1.0);
        put("cockapoo", 1.0);
        put("coonhound", 1.0);
        put("cotondetulear", 1.0);
        put("dachshund", 1.0);
        put("dalmatian", 1.0);
        put("dhole", 1.0);
        put("dingo", 1.0);
        put("doberman", 1.0);
        put("entlebucher", 1.0);
        put("eskimo", 1.0);
        put("germanshepherd", 1.0);
        put("groenendael", 1.0);
        put("havanese", 1.0);
        put("husky", 1.0);
        put("keeshond", 1.0);
        put("kelpie", 1.0);
        put("komondor", 1.0);
        put("kuvasz", 1.0);
        put("labrador", 1.0);
        put("leonberg", 1.0);
        put("lhasa", 1.0);
        put("malamute", 1.0);
        put("malinois", 1.0);
        put("maltese", 1.0);
        put("mexicanhairless", 1.0);
        put("mix", 1.0);
        put("newfoundland", 1.0);
        put("otterhound", 1.0);
        put("papillon", 1.0);
        put("pekinese", 1.0);
        put("pembroke", 1.0);
        put("pitbull", 1.0);
        put("pomeranian", 1.0);
        put("pug", 1.0);
        put("puggle", 1.0);
        put("pyrenees", 1.0);
        put("redbone", 1.0);
        put("rottweiler", 1.0);
        put("saluki", 1.0);
        put("samoyed", 1.0);
        put("schipperke", 1.0);
        put("shiba", 1.0);
        put("shihtzu", 1.0);
        put("stbernard", 1.0);
        put("vizsla", 1.0);
        put("weimaraner", 1.0);
        put("whippet", 1.0);
        put("australian/shepherd", 1.0);
        put("buhund/norwegian", 1.0);
        put("bulldog/boston", 1.0);
        put("bulldog/english", 1.0);
        put("bulldog/french", 1.0);
        put("bullterrier/staffordshire", 1.0);
        put("cattledog/australian", 1.0);
        put("collie/border", 1.0);
        put("corgi/cardigan", 1.0);
        put("dane/great", 1.0);
        put("deerhound/scottish", 1.0);
        put("elkhound/norwegian", 1.0);
        put("finnish/lapphund", 1.0);
        put("frise/bichon", 1.0);
        put("greyhound/italian", 1.0);
        put("hound/afghan", 1.0);
        put("hound/basset", 1.0);
        put("hound/blood", 1.0);
        put("hound/english", 1.0);
        put("hound/ibizan", 1.0);
        put("hound/plott", 1.0);
        put("hound/walker", 1.0);
        put("mastiff/bull", 1.0);
        put("mastiff/english", 1.0);
        put("mastiff/tibetan", 1.0);
        put("mountain/bernese", 1.0);
        put("mountain/swiss", 1.0);
        put("ovcharka/caucasian", 1.0);
        put("pinscher/miniature", 1.0);
        put("pointer/german", 1.0);
        put("pointer/germanlonghair", 1.0);
        put("poodle/miniature", 1.0);
        put("poodle/standard", 1.0);
        put("poodle/toy", 1.0);
        put("retriever/chesapeake", 1.0);
        put("retriever/curly", 1.0);
        put("retriever/flatcoated", 1.0);
        put("retriever/golden", 1.0);
        put("ridgeback/rhodesian", 1.0);
        put("schnauzer/giant", 1.0);
        put("schnauzer/miniature", 1.0);
        put("setter/english", 1.0);
        put("setter/gordon", 1.0);
        put("setter/irish", 1.0);
        put("sheepdog/english", 1.0);
        put("sheepdog/shetland", 1.0);
        put("spaniel/blenheim", 1.0);
        put("spaniel/brittany", 1.0);
        put("spaniel/cocker", 1.0);
        put("spaniel/irish", 1.0);
        put("spaniel/japanese", 1.0);
        put("spaniel/sussex", 1.0);
        put("spaniel/welsh", 1.0);
        put("springer/english", 1.0);
        put("terrier/american", 1.0);
        put("terrier/australian", 1.0);
        put("terrier/bedlington", 1.0);
        put("terrier/border", 1.0);
        put("terrier/dandie", 1.0);
        put("terrier/fox", 1.0);
        put("terrier/irish", 1.0);
        put("terrier/kerryblue", 1.0);
        put("terrier/lakeland", 1.0);
        put("terrier/norfolk", 1.0);
        put("terrier/norwich", 1.0);
        put("terrier/patterdale", 1.0);
        put("terrier/russell", 1.0);
        put("terrier/scottish", 1.0);
        put("terrier/sealyham", 1.0);
        put("terrier/silky", 1.0);
        put("terrier/tibetan", 1.0);
        put("terrier/toy", 1.0);
        put("terrier/westhighland", 1.0);
        put("terrier/wheaten", 1.0);
        put("terrier/yorkshire", 1.0);
        put("waterdog/spanish", 1.0);
        put("wolfhound/irish", 1.0);
    }};
}
